const chalk = require('chalk');

const currentDir = process.cwd();

let drupalbuild = {};
try {
  drupalbuild = require(currentDir + '/.drupalbuild.js');
} catch (error) {
  // no error.
}

if (Array.isArray(drupalbuild)) {
  // Old configuration format.
  console.warn(chalk.yellow(`NOTE: The array format of ${chalk.bold('.drupalbuild.js')} is deprecated, please update it.`));
  drupalbuild = {
    ignoreList: drupalbuild,
  };
}

// The current drupal build settings.
module.exports = {
  ignoreList: [],
  watchSettings: {},
  sassSettings: {},
  jsHeader: `DO NOT EDIT THIS FILE.\nSee the following change record for more information,\nhttps://www.drupal.org/node/2815083\n@preserve`,
  cssHeader: `/**\n * Don't edit this file. Find all style at ./sass folder.\n **/\n`,
  ...drupalbuild,
  files: {
    jsSrc: './**/*.es6.js',
    jsDestination: './', // Relative to the current es6.js file.
    scssSrc: './css/**/[!_]*.scss',
    scssDestination: '../',  // Relative to the current scss file.
    ...drupalbuild.files,
  },
};
